;Z REVEAL   --      "reveal" latest definition  Flashable
HEADER(XT_REVEAL,6,"reveal",DOCOLON)
        DW XT_NEWEST,XT_FETCH
	DW XT_QDUP,XT_DOCONDBRANCH
	DEST(REVEAL1)
	DW XT_NEWEST,XT_CELLPLUS,XT_FETCH,XT_STORE
	DW XT_ZERO,XT_NEWEST,XT_STORE
REVEAL1:
	DW XT_EXIT
