; These words not part of the essentials
; but written in assembly language / notoation

; simple stack dump
.include "words/dot-s.asm"

; next some words that may be useful in certain
; applications only

;; wordlist management.
;.include "words/infodp.asm"
;.include "words/wordlist.asm"
;.include "words/set-order.asm"
;.include "words/get-order.asm"
;.include "words/set-current.asm"

;; double cell arithmetics
;.include "words/d-plus.asm"
;.include "words/d-minus.asm"

;; some (external) assembly required
;.include "words/code.asm"
;.include "words/end-code.asm"

;; compiler
;.include "words/bracketcompile.asm"

;; text interpreter
;.include "words/get-recognizer.asm"
;.include "words/set-recognizer.asm"
;.include "words/name2interpret.asm"
;.include "words/name2compile.asm"

;; legacy words
;.include "words/word.asm"
;.include "words/count.asm"
