#
# all secondaries / colon words
# they represend data instead of code
#

.include "words/warm.s"
.include "words/ms.s"
.include "words/cr.s"
.include "words/bl.s"
.include "words/space.s"
.include "words/spaces.s"
.include "words/zero.s"
.include "words/left-bracket.s"
.include "words/decimal.s"
.include "words/hex.s"

.include "words/pad.s"
.include "words/here.s"
.include "words/hold.s"
.include "words/sharp.s"
.include "words/sign.s"
.include "words/dot.s"
.include "words/d-dot-r.s"
.include "words/d-dot.s"
.include "words/u-dot.s"
.include "words/ud-dot.s"
.include "words/ud-dot-r.s"

.include "words/dot-s.s"

.include "words/refill.s"
.include "words/accept.s"
.include "words/prompt-error.s"
.include "words/prompt-input.s"
.include "words/prompt-ok.s"
.include "words/prompt-ready.s"

.include "words/catch.s"
.include "words/throw.s"
.include "words/source.s"
.include "words/q-stack.s"
.include "words/cscan.s"
.include "words/cskip.s"
.include "words/parse-name.s"
.include "words/slash-string.s"

.include "words/2literal.s"
.include "words/literal.s"
.include "words/compile.s"
.include "words/comma.s"
.include "words/immediate-q.s"
.include "words/find-xt.s"
.include "words/nfa2lfa.s"
.include "words/nfa2cfa.s"
.include "words/traverse-wordlist.s"
.include "words/show-wordlist.s"
.include "words/search-wordlist.s"
.include "words/name2string.s"
.include "words/name2flags.s"

.include "words/rec-null.s"
.include "words/rec-find.s"
.include "words/rec-split.s"
.include "words/forth-recognizer.s"
.include "words/recognize.s"

.include "words/interpret.s"
.include "words/map-stack.s"
.include "words/qdo.s"

.include "words/init-ram.s"
.include "words/ver.s"

.include "words/count.s"
.include "words/type.s"

.include "words/words.s"
.include "dict_appl.inc"
