; ( -- f )
    DEFER(XT_REFILL,6,"refill")
	DW USER_REFILL+UAREA
	DW XT_RDEFERFETCH
	DW XT_RDEFERSTORE

    HEADLESS(XT_TIB_REFILL,DOCOLON)
        DW XT_TIB,XT_TIBSIZE,XT_ACCEPT
	DW XT_NUMBERTIB, XT_STORE
	DW XT_ZERO,XT_TO_IN,XT_STORE
	DW XT_MINUSONE,XT_EXIT
