#
# all secondaries / colon words
# they represend data instead of code
#

.include "words/warm.s"
.include "words/ms.s"
.include "words/cr.s"
.include "words/bl.s"
.include "words/space.s"
.include "words/spaces.s"
.include "words/zero.s"
.include "words/left-bracket.s"
.include "words/decimal.s"
.include "words/hex.s"

.include "words/pad.s"
.include "words/here.s"
.include "words/hold.s"
.include "words/sharp.s"
.include "words/sign.s"
.include "words/dot.s"
.include "words/d-dot-r.s"
.include "words/d-dot.s"
.include "words/u-dot.s"
.include "words/ud-dot.s"
.include "words/ud-dot-r.s"

.include "words/refill.s"
.include "words/accept.s"
.include "words/prompt-error.s"
.include "words/prompt-input.s"
.include "words/prompt-ok.s"
.include "words/prompt-ready.s"

.include "words/catch.s"
.include "words/throw.s"
.include "words/interpret.s"

.include "words/init-ram.s"
.include "words/ver.s"

.include "words/count.s"
.include "words/type.s"

.include "dict_appl.inc"
