#
# all secondaries / colon words
# they represend data instead of code
#

.include "words/warm.s"
.include "words/ms.s"
.include "words/cr.s"
.include "words/bl.s"
.include "words/space.s"
.include "words/spaces.s"
.include "words/zero.s"
.include "words/left-bracket.s"
.include "words/decimal.s"
.include "words/hex.s"

.include "words/pad.s"
.include "words/hold.s"
.include "words/sharp.s"

.include "words/ver.s"
